#variables task1
# "/home/user/Desktop" example path
task1_path =
run-task1:
	sudo bash ../task-1/undublicate-v1.sh $(task1_path)

run-task2:
	sudo bash ../task-2/exctract_code.sh

#variables task3
# myuser
user=myuser
# example.com
host=example.com
run-task3:
	sudo bash ../task-3/configure-ssh.sh $(user) $(host)

#example path/DevOpsTeamTasks/linux-assignment/task-4/main
run_command_task4=
run-task4:
	sudo bash ../task-4/logrotate_setup.sh $(run_command_task4)

#example path/DevOpsTeamTasks/linux-assignment/task-4
app_folder =/home/fifs/Documents/DevOpsTeamTasks/linux-assignment/task-4
#example /app/main
run_command_task5 = /app/main
run-task5:
	sudo bash ../task-5/service.sh $(app_folder) $(run_command_task5)

run-task6:
	bash ../task-6/top-n-heaviest-files.sh


run-task7:
	sudo bash ../task-7/service_timer.sh

file_path=
new_job_name=
run-task8:
	sudo bash ../task-8/change-job-name.sh $(file_path) $(new_job_name)

#example: -h, -a, -d
option =
run-task9:
	sudo bash ../task-9/close_network.sh $(option)

ip_address =
domain =
run-task10:
	sudo bash ../task-10/add_dns.sh $(ip_address) $(domain)

number_of_instances =
run-task11:
	sudo bash ../task-11/run_api_instances.sh $(number_of_instances)









