#! /bin/bash

sudo useradd kafka -m

# thinks that kafka already installed in /opt/kafka
sudo chown -R kafka:kafka /opt/kafka

# by default setups 3 kafka instances

sudo cp templates/zookeeper.service /etc/systemd/system/zookeeper.service

for i in 1 2 3
do
    sudo cp config/broker.properties /opt/kafka/config/broker$i.properties
    sudo sed -i "s/broker.id=0/broker.id=$i/" /opt/kafka/config/broker$i.properties
    sudo sed -i "s/listeners=PLAINTEXT:\/\/:9092/listeners=PLAINTEXT:\/\/:909$i/" /opt/kafka/config/broker$i.properties
    sudo sed -i "s/advertised.listeners=PLAINTEXT:\/\/192.168.65.3:9092/advertised.listeners=PLAINTEXT:\/\/192.168.65.3:909$i/" /opt/kafka/config/broker$i.properties
    sudo sed -i "s/log.dirs=C:\/kafka\/kafka-logs/log.dirs=\/opt\/kafka\/C:\/kafka\/kafka-logs$i/" /opt/kafka/config/broker$i.properties
    sudo sed -i "s/offsets.topic.replication.factor=1/offsets.topic.replication.factor=3/" /opt/kafka/config/broker$i.properties

    sudo cp templates/broker.service /etc/systemd/system/kafka-broker$i.service
    sudo sed -i "s/ExecStart=\/opt\/kafka\/bin\/kafka-server-start.sh \/opt\/kafka\/config\/broker.properties/ExecStart=\/opt\/kafka\/bin\/kafka-server-start.sh \/opt\/kafka\/config\/broker$i.properties/" /etc/systemd/system/kafka-broker$i.service
done

sudo systemctl daemon-reload

sudo systemctl enable zookeeper
sudo systemctl start zookeeper

for i in 1 2 3
do
    sudo systemctl enable kafka-broker$i
    sudo systemctl start kafka-broker$i
done
