stages:
  - deploy

deploy:
  stage: deploy
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apk add --update openssh )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan $VM_IPADDRESS >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - ssh $SSH_USER@$VM_IPADDRESS  <<EOF
    - sudo rm -rf app
    - git clone $CI_REPOSITORY_URL app
    - cd app
    - sudo apt-get update
    - sudo apt-get install python3 python3-pip virtualenv -y
    - virtualenv venv
    - source venv/bin/activate
    - python3 -m pip install -r requirements.txt
    - sudo cp ./test.service /etc/systemd/system/test.service
    - sudo systemctl daemon-reload
    - sudo systemctl start test
    - EOF
  after_script:
    - "curl -s -X POST https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage -d chat_id=\"$TELEGRAM_CHAT_ID\" -d text=\"CI/CD pipeline has been completed for $CI_COMMIT_REF_NAME branch. Status: $CI_JOB_STATUS\""
  only:
    - main
    - /^release-.*$/
  environment:
    name: production
    url: http://$VM_IPADDRESS:8000
  when:
    manual
