FROM --platform=linux/amd64 ubuntu:bionic-20180410

ENV DEBIAN_FRONTEND=noninteractive
ENV DISPLAY=host.docker.internal:0

RUN apt-get update && apt-get install -y wget

RUN wget http://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_129.0.6668.100-1_amd64.deb -O chrome.deb

RUN apt-get install -y ./chrome.deb

RUN rm chrome.deb

CMD ["google-chrome", "--no-sandbox", "--disable-gpu", "https://yandex.ru/games/"]