version: "3.8"
services:
  minio:
    image: nginx:1.19.2-alpine
    container_name: minio
    hostname: minio.local
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
