#! /bin/bash

docker network create task-5-test
docker network inspect task-5-test | jq '.[0].IPAM.Config[0].Subnet'


docker run -d --rm --name "task-5-traefik" -p 80:80 -p 8080:8080 -v ./traefik/traefik.yml:/traefik.yml -v /var/run/docker.sock:/var/run/docker.sock:ro --network task-5-test traefik:v2.10 --providers.docker=true --providers.docker.exposedbydefault=false --entrypoints.web.address=:80 --api.insecure=true