run:
  concurrency: 4
  allow-parallel-runners: true
output:
  formats:
    - format: colored-line-number
      path: stderr
linters:
  disable-all: true
  enable:
    - errcheck
    - bodyclose
    - godox
    - govet