#! /bin/bash

if ! [ -x "$(command -v docker)" ]; then
  echo "Error: Docker is not installed." >&2
  exit 1
fi

mkdir -p /var/lib/docker-viper

cp docker-viper.sh /var/lib/docker-viper/docker-viper.sh
cp docker-viper.service /etc/systemd/system/docker-viper.service
cp docker-viper.timer /etc/systemd/system/docker-viper.timer

systemctl daemon-reload

systemctl enable docker-viper.timer
systemctl start docker-viper.timer

echo "Docker Viper has been installed successfully."
