#! /bin/bash

if ! [ -x "$(command -v docker)" ]; then
  echo "Error: Docker is not installed." >&2
  exit 1
fi

cp /var/lib/docker-viper/docker-viper.service /etc/systemd/system/docker-viper.service
cp /var/lib/docker-viper/docker-viper.timer /etc/systemd/system/docker-viper.timer

systemctl daemon-reload

systemctl enable docker-viper.timer
systemctl start docker-viper.timer

echo "Docker Viper has been installed successfully."
