---
- name: Install Nomad locally
  hosts: localhost
  become: yes
  connection: local

  tasks:
    - name: Download and add HashiCorp GPG key
      ansible.builtin.command:
        cmd: wget -O - https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
      args:
        creates: /usr/share/keyrings/hashicorp-archive-keyring.gpg

    - name: Add HashiCorp repository
      ansible.builtin.copy:
        dest: /etc/apt/sources.list.d/hashicorp.list
        content: |
          deb [arch=amd64 signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main
      register: hashicorp_repo

    - name: Update APT cache
      ansible.builtin.apt:
        update_cache: yes
      when: hashicorp_repo.changed

    - name: Install Nomad
      ansible.builtin.apt:
        name: nomad
        state: present
